У завданнях 1-4. Вам наданий простий код на Python, який не відповідає вказівкам PEP8. Ваше завдання — відредагувати код так, аби він відповідав PEP8. Напишіть після редагуванню коду, дотримання яких правил з pep8 ви досягли в відредагованій версі, наприклад
```
- додала пробіли навколо бінарного оператора
- додала два порожні рядки між визначеннями функцій
і тд
```
Також можна зазанчити використані правила коментарями по коду, а не окремим повідомленням.

Відредагований код має виконувати весь той самий функціонал, але бути написаний відповідно до вимог до гарного коду на Python! Не забудьте запустити відредагований код, він має бути робочим.

Завдання 1.

In [ ]:
def greet(name):print(f"Hello, {name}")
def add(n1,n2):return n1+n2

x = 5;y = 3
display(greet("John"),add(x,y))

Hello, John

None

8

In [ ]:
# кожна інструкція з нового рядка
def greet(name):
    print(f"Hello, {name}")

# зрозумілі назви параметрів, порожні рядки між функціями
def add(number1, number2):
    return number1 + number2

#немає кількох команд в одному рядку
x = 5
y = 3

# розділяємо функції, адже одна друкує і нічого не повертаєб заміна display на print
greet("John")

print(add(x, y))

Hello, John
8

Завдання 2.

In [ ]:
from math import *
def calcArea(r):return pi*r**2
def calcCircumference(r):return 2*pi*r

radius=5
print("Area:",calcArea(radius),"Circumference:",calcCircumference(radius))

Area: 78.53981633974483 Circumference: 31.41592653589793

In [ ]:
from math import pi

def calc_area(radius):
    return pi * radius ** 2


def calc_circumference(radius):
    return 2 * pi * radius


radius = 5

area = calc_area(radius)
circumference = calc_circumference(radius)

print(f"Area: {area:.2f}")
print(f"Circumference: {circumference:.2f}")

Area: 78.54
Circumference: 31.42

- імпортували тільки потрібне
- назви функцій у snake_case.
- повна назва змінної radius робить код зрозумілішим.
- пробіли навколо операторів (=, *, **)
- одна команда перенесена на окремий рядок
- порожні рядки між функціями
- розділено довгий print() на два окремі print()
- округлення результату

Завдання 3.

In [ ]:
class animal: pass
class dog(animal):
    def __init__(self,name):
        self.name=name
        self.type='Dog'

In [ ]:
class Animal:
    pass


class Dog(Animal):
    def __init__(self, name):
        self.name = name
        self.type = "Dog"

- працюємо з класами, а їхні назви потрібно у PascalCase
- порожні рядки між класами
- пробіли навколо =
- пробіли після ком

Завдання 4.

In [ ]:
list=[1,2,3,4,5]
for i in range(len(list)):print(list[i])

1
2
3
4
5

In [ ]:
numbers = [1, 2, 3, 4, 5]

for i in range(len(numbers)):
    print(numbers[i])

1
2
3
4
5

In [ ]:
numbers = [1, 2, 3, 4, 5]

for number in numbers:
    print(number)

1
2
3
4
5

- змінено назву змінної list → numbersб не можна назвиати як вбудовані типи Python
- пробіли після ком s пробіли навколо =
- print() перенесений на новий рядок
 - відступ у циклі
 Додактово показаний більш правильний Python-варіант циклу без len ()

5.У вас є DataFrame df, що представляє результати тестів студентів з математики, англійської мови та історії. Поточний код обчислює середній бал для кожного студента шляхом ітерації за рядками DataFrame за допомогою iterrows().

Ваше завдання полягає в тому, щоб змінити код так, аби уникнути використання iterrows() і замість цього застосувати більш ефективне та читабельне рішення відповідно до правил, озвучених у лекції. Рефакторинг треба зробити лише частині, де рахуються середні, імпорт і визначення датафрейму лишаємо без змін.

In [1]:
import pandas as pd

df = pd.DataFrame({
    'student': ['Alice', 'Bob', 'Charlie', 'David'],
    'math_score': [89, 94, 77, 85],
    'english_score': [92, 88, 79, 85],
    'history_score': [84, 92, 81, 89]
})

In [2]:
averages = []
for _, row in df.iterrows():
    averages.append((row['math_score'] + row['english_score'] + row['history_score']) / 3)

df['average_score'] = averages

In [ ]:
df['average_score'] = df[
    ['math_score', 'english_score', 'history_score']
].mean(axis=1)

In [3]:
df

   student  math_score  english_score  history_score  average_score
0    Alice          89             92             84      88.333333
1      Bob          94             88             92      91.333333
2  Charlie          77             79             81      79.000000
3    David          85             85             89      86.333333

6.У Вас є великий DataFrame df, що представляє транзакції продажу в магазині. Цей DataFrame містить понад 1 мільйон рядків і кілька стовпців, зокрема «product_name», «product_category», «product_price» і «transaction_date».

І «product_name», і «product_category» є рядками, що представляють численні, але обмежені унікальні назви продуктів і категорії відповідно.

Напишіть код для ефективного перетворення стовпців «product_name» і «product_category» на категорійний тип для ефективного використання пам’яті.
Спробуйте вирішити це завдання, мінімізуючи використання пам'яті та зберігаючи читабельність коду. Крім того, виміряйте використання пам’яті до та після перетворення, щоб продемонструвати підвищення ефективності.

Порівняйте кількість памʼяті, яку займає наданий набір даних і новий, створений Вами. В лекції був приклад. В скільки разів менше памʼяті займає новий датафрейм?

In [4]:
import pandas as pd
import numpy as np

np.random.seed(0)

products = ['apple', 'banana', 'cherry', 'dates', 'elderberry']
categories = ['fruit', 'fruit', 'fruit', 'fruit', 'fruit']

N_ROWS = 10**6
df = pd.DataFrame({
    'product_name': np.random.choice(products, N_ROWS),
    'product_category': np.random.choice(categories, N_ROWS),
    'product_price': np.random.uniform(1, 10, N_ROWS),
    'transaction_date': pd.date_range(start='1/1/2000', periods=N_ROWS, freq='h')
})

In [5]:
df.memory_usage(index=False).sum()

np.int64(32000000)

In [14]:
memory_before = df.memory_usage(deep=True).sum()
memory_before

np.int64(125398524)

df.memory_usage(index=False).sum() Рахує пам'ять для стовпців DataFrame без індексу.df.memory_usage(deep=True).sum() Рахує реальне використання пам'яті, включаючи: самі рядки (object), внутрішні структури Python, словники категорій (category), індекс (якщо не вимкнений)

In [7]:
df.product_name

0         elderberry
1              apple
2              dates
3              dates
4              dates
             ...
999995         apple
999996         dates
999997        banana
999998         apple
999999        cherry
Name: product_name, Length: 1000000, dtype: object

In [10]:
df_optimized = df.copy()

#варіант через astype
df_optimized[['product_name', 'product_category']] = (
    df_optimized[['product_name', 'product_category']]
    .astype('category')
)

#варіант через pd.Categorical

for column in ['product_name', 'product_category']:
    df_optimized[column] = pd.Categorical(df_optimized[column])

df_optimized.memory_usage(index=False).sum()

np.int64(18000328)

In [15]:
memory_after = df_optimized.memory_usage(deep=True).sum()
memory_after

np.int64(18000743)

In [16]:
reduction = (1 - memory_after / memory_before) * 100

print(f"Маємо зниження витрат памʼяті на {reduction:.2f}%!")

Маємо зниження витрат памʼяті на 85.65%!

7.В цьому завданні кілька пунктів. Треба виконати усі послідовно.   
    7.1. Завантажте дані у pandas dataframe з файла `ecommerce_data.csv`. Обовʼязково при завантаженні вкажіть параметр `encoding = 'ISO-8859-1'`, без нього буде помилка.  
    7.2. Заповніть пропущені значення в колонці CustomerID на -1 та перетворіть тип цієї колонки на str, адже зараз вона типу float, а це не правильний тип даних для ідентифікатора клієнта.  
    7.3. З допомогою бібліотеки sweetviz побудуйте html звіт, який порівнює дані для країни "Germany" і країни "France". У Вас можуть виникнути багато попереджень (Warning), їх рекомендую вимкнути наступним шматком коду   
    
   
    import warnings

    with warnings.catch_warnings(record=True):
        # your code
    
    
   7.4.Напишіть 5 відмінностей для двох зазначених країн на основі побудованого звіту, без виконання додаткового аналізу іншими інструментами.

8.З допомогою ChatGPT виявіть, чи є та які помилки в наступному коді.  
Попросіть після цього переписати код із дотриманням PEP8. Проаналізуйте результат. Чи справді ChatGPT виправив всі стилістичні помилки? Якщо ні, напишіть йому ще кілька запитів, аби код відповідав вимогам PEP8.  
Вставте фінальну версію коду з чату у ноутбук та запустіть на заданому списку. Має вертатись 50.  
Напишіть, які промпти (інструкції) при зверненні до ChatGPT ви застосували та додайте скріншот(-и) з промптами та відповідями чата.  
Якщо зробили висновки при виконанні цього завдання, то діліться також :)

**ЯК ВСТАВИТИ СКРІНШОТ в Jupyter Notebook** :
1. Створіть нову Markdown клітинку
2. В новоствореній клітинці обираєте в меню Jupyter Notebook Edit -> Insert Image
3. Обираєте картинку
4. В клітинці має зʼявитись текст, який містить картинку. Запустіть клітинку.

Або можна просто перетягнути картинку в Markdown клітинку.

In [ ]:
def CalculateVariance(nl):
    sum_list = 0
    for n in nl:
        sum_list = sum_list + n
    mean = sum_list / len(nl)
    sum_squares = 0
    for n in nl:
        sum_squares = sum_squares + n**2
    mean_squares = sum_squares / len(nl)
    return mean_squares

In [ ]:
input_list = [75, 80, 85, 90, 95]